### ISSUE TITLE
Errors with meteor

### ISSUE THREAD

**Issue by LiShine** [deepsweet/hocs#11]
Hi
I used withLog version 0.2, all is fine.
But version 0.3, even after updating recompose from 0.25.1 to 0.26, gives with Meter a lot of errors with
Uncaught TypeError: Cannot read property 'meteorInstall' of undefined
I really have no clue what it is even after googling

**Comment by deepsweet** [comment]
Meteor?.. could you please explain a bit how it's related to React and HOCs? I have zero experience with Meteor and its ecosystem.

The only thing I can try to guess: Meteor bundler (something similar to Webpack, have no idea) doesn't support 1) `browser` field in `package.json` 2) ES Modules, i.e. transpiling ES6 `import`/`export` by itself (usually a requirement for Tree Shaking feature).

Also, more detailed stack trace could help.

Thanks!

**Comment by deepsweet** [comment]
Feel free to re-open this when you have time to reply.
