### ISSUE TITLE
@hocs/with-lifecycle@0.4.0 depends on older recompose version

### ISSUE THREAD

**Issue by andyperisho** [deepsweet/hocs#16]
```
warning " > @hocs/with-lifecycle@0.4.0" has incorrect peer dependency "recompose@^0.26.0".
```

Should we not update the `recompose` dependency to `0.27.0` instead of `0.26.0`?

**Comment by deepsweet** [comment]
Fixed with v0.5.0, `recompose` is no longer a peer dependency of this HOC at all (the rest of HOCs will get rid of it too).
