### ISSUE TITLE
[QUESTION] - Why don't use just `isOnline`? 

### ISSUE THREAD

**Issue by luan0ap** [deepsweet/hocs#18]
In the `with-online-status-props` component, why don't use just `isOnline` property in state? If is offline soon will not `true`, in the `isOnline` property

```
this.state = mapStatusToProps({
        isOnline: global.navigator.onLine,
        isOffline: !global.navigator.onLine
      })
```

**Comment by deepsweet** [comment]
Hi.

That's the internal state and implementation. From outside:

```js
const Demo = (props) => (
  <h1>props: {JSON.stringify(props)}</h1>
);

export default withOnlineStatusProps(
  ({ isOnline, isOffline }) => ({ isOnline, isOffline })
)(Demo)
```

What you return there is what you get as props, zero or many.

Feel free to continue conversation here even if the issue is closed :)
