### ISSUE TITLE
React warning raised when using OnReceivedProps

### ISSUE THREAD

**Issue by ekaradon** [deepsweet/hocs#27]
Hello,

When using your great addition plugin to recompose, I see the following warning:
`It is not recommended to assign props directly to state because updates to props won't be reflected in state. In most cases, it is better to use props directly.`

See the example here (look at the debugger warning):
https://codesandbox.io/s/beautiful-merkle-ldcxs
![Screenshot_20190523_183526](https://user-images.githubusercontent.com/9439390/58270225-8eb92280-7d89-11e9-803d-3bff5cf57883.png)

Is it possible to fix this? Could I help?

Regards,

**Comment by deepsweet** [comment]
Thanks! Fixed in `with-lifecycle@0.5.1`

**Comment by ekaradon** [comment]
Thanks! :+1:
