### ISSUE TITLE
'recompose' does not contain an export named 'createEagerFactory'

### ISSUE THREAD

**Issue by barbalex** [deepsweet/hocs#9]
This error occurs in the console when running `npm run build` after updating recompose from v0.25.1 to v0.26.0

    PS C:\Users\alex\apf2> npm run build

    > apf2@0.1.0 build C:\Users\alex\apf2
    > react-scripts build

    Creating an optimized production build...
    Failed to compile.

    ./node_modules/@hocs/with-lifecycle/es/index.js
    14:18-36 'recompose' does not contain an export named 'createEagerFactory'.

**Comment by deepsweet** [comment]
That's because peer dependency for recompose is still `^0.25.0` for all packages, i.e. we are not ready for that breaking change yet. I'll update it pretty soon, thanks for reminder.

**Comment by barbalex** [comment]
well, thanks for your great tools and willingness to work sundays for all of us!

**Comment by deepsweet** [comment]
Will land as `with-lifecycle@0.3.0` as soon as I implement `componentDidCatch` 🎉  Most likely today or tomorrow.

**Comment by deepsweet** [comment]
[Done](https://github.com/deepsweet/hocs/releases/tag/with-lifecycle%400.3.0).
